### ISSUE TITLE
[javascript] main Page

### ISSUE THREAD

**Issue by Blair-0404** [woowa-techcamp-2020/market-9-blair-dnacu#13]
메인페이지에는 아무런 내용이 없고 로그인,회원가입 화면만 제공한다. 아이디/비밀번호 찾기는 동작하지 않는다.

- [x] 회원가입 페이지로 이동하기
- [x] 로그인 페이지로 이동하기

**Comment by dnacu** [comment]
Commit ref: bd08db96a568183a062a112feafed5af1ca7ab39
