### ISSUE TITLE
[javascript] signIn Page

### ISSUE THREAD

**Issue by Blair-0404** [woowa-techcamp-2020/market-9-blair-dnacu#14]
- [x] 로그인 과정에서의 오류체크는 회원가입에서 진행했던 것과 유사하게 임의로 오류조건을 만들어서 체크한다.

- [x] 로그인 이후에는 다시 메인페이지로 이동한다.

- [x] 메인페이지의 구성은 기획서에서 별도 제시하지 않으며, 로그인 됐다는 메시지만 자유롭게 노출한다.

- [x] 아이디 저장기능을 구현한다.

**Comment by dnacu** [comment]
Commit ref: d594da2dcefd1551ac26fa8e911b35acaa966752
