### ISSUE TITLE
[Arrange files] 폴더링 및 파일 구조화 작업 필요

### ISSUE THREAD

**Issue by Blair-0404** [woowa-techcamp-2020/market-9-blair-dnacu#6]
[Arrange files] 폴더링 및 파일 구조화 작업 필요

- [x] 페이지별로 혹은  MVC패턴적용하는 등의 폴더링 작업이 필요합니다.

**Comment by dnacu** [comment]
Commit ref: [x] 4ad3232ac0563b766a1f827f6048c1510b3cefab
